networks:
  redstone-mainnet:
    - name: mainnet
      chainid: 690
      rpc: https://rpc.redstonechain.com
  redstone-testnet:
    - name: holesky
      chainid: 17069
      rpc: https://rpc.garnetchain.com
        
worlds:
  redstone-mainnet:
       - name: cafecosmos-mainnet
  redstone-testnet:
       - name: cafecosmos-testnet
       - address: "0x0209FE2b6C1a2B8cE12D8d9D6cf2D78a3Ff324FE"