name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi  # Associate this job with the 'pypi' environment

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.USERNAME }}  # Uses the USERNAME secret from the 'pypi' environment
        TWINE_PASSWORD: ${{ secrets.PASSWORD }}  # Uses the PASSWORD secret from the 'pypi' environment
      run: twine upload dist/*
